[window]
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "OnlyRight"

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

# defaults -currentHost write -g AppleFontSmoothing -int 0
[font]
size = 16.0

[font.normal]
family = "Fira Code"
style = "Retina"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "F11", mods = "Command", action = "Copy" },
  { key = "F12", mods = "Command", action = "Paste" }
]
